### ISSUE TITLE
Show default value for keys with subkeys in a comment

### ISSUE THREAD

**Issue by chrispyles** [chrispyles/fica#25]
If a key has a default value that is not an instance of its subkey container, e.g.

```python
foo = fica.Key(default=False, subkey_container=FooValue)
```

then in the documentation show the default value in a comment above the subkeys:

```yaml
foo:  # some description
  # default: false
  bar: 1  # some description
  baz: 2  # some description
```
